---
title: 'Chamber Check Visualization'
author: "Anastasia Bernat"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
rm(list=ls())
setwd("~/Desktop/Rstats-winter2020/")
library(lubridate)
library(chron)
library(dplyr)
library(randomcoloR)
knitr::opts_chunk$set(echo = TRUE)
```

# Loading, cleaning, and recoding the data

```{r echo=FALSE}
source("src/clean_flight_data.R") 
source("src/center_flight_data.R")
data <- read_flight_data("data/all_flight_data-Winter2020.csv")
data_all <- data[[1]]
data_tested <- data[[2]]
```

**Checking errors** 

How to check for flight time errors? Check for the sucessive intervals for when bugs were placed into and out of the chamber for testing. This visual shows that for each day (or set) for each chamber (just horizontal lines drawn with the filename on top and different colors). 

```{r fig.width=11, fig.height=6}

sets <- unique(data_tested$set_number)

for(set in sets) {
  dataA <- filter(data_tested, set_number == set, as.character(channel_letter) == "A" )
  dataA$start_time <- strptime(dataA$time_start, format="%H:%M:%S")
  dataA <- dataA[order(dataA$chamber, dataA$start_time),] 

  dataB <- filter(data_tested, set_number == set, as.character(channel_letter) == "B" )
  dataB$start_time <- strptime(dataB$time_start, format="%H:%M:%S")
  dataB <- dataB[order(dataB$chamber, dataB$start_time),] 
  
  data_list <- list(dataA, dataB)

  png(paste0("output/set", set, ".png"), width = 2100, height = 1050)
  par(mfrow=c(2,1))
  for(data in data_list) {
    rand_colors <- randomColor(nrow(data), luminosity="bright")

    max_x <- max(as.duration(hms(data$time_end))) 
    min_x <- min(as.duration(hms(data$time_start)))
  
    plot(1, type="n", xlim=c(min_x, max_x), ylim=c(0.5, 4.8), xlab="Duration (s)", ylab="Channel Number")
    for(row in 1:nrow(data)) {
      
      if(row %% 2 == 0) {
        pos <- 1
        direction <- -1}
      else{
        pos <- 3
        direction <- 1}
      
      channel <- as.character(data$chamber[row])
      channel_num <- as.numeric(sapply(strsplit(channel, "-"), "[[", 2))
      channel_letter <- sapply(strsplit(channel, "-"), "[[", 1)
      filename <- data$filename[row]
      set_num <- data$set_number[row]
      start_time <- hms(data$time_start[row])
      end_time <- hms(data$time_end[row])
      
      lines(c(start_time, end_time), c(channel_num, channel_num), type="l", col=rand_colors[row])
      text(c(start_time, end_time), c(channel_num, channel_num), labels=as.character(c(start_time, end_time)), 
                                                                  cex=0.8, font=2, pos=pos, col=rand_colors[row])
      midpoint <- as.duration(start_time + end_time ) / 2
      file <- sprintf("[%s]", filename)
      text(midpoint, channel_num + 0.2*direction, labels=file, cex=0.65, font=2, pos=pos, col=rand_colors[row]) #0.09* direction if don't squish
    }
    title(main=paste("Channel Letter", channel_letter))
  }
  dev.off()
}
```