---
title: "Tables - Flight Trials Winter 2020 "
author: "Anastasia Bernat"
date: "8/4/2020"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
setwd("/Users/anastasiabernat/Desktop/git_repositories/SBB-dispersal/avbernat_working_on/Dispersal/Winter_2020/stats")

library(lme4)
library(dplyr)
library(ggplotify)
library(gridExtra)
library(ggformula)
library(tidyselect)
library(zoo)
library(knitr)
library(kableExtra)
library(webshot)

knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, message=FALSE}
output_col = FALSE # Recommend changing this to TRUE if working in Base R or RStudio, and FALSE if generating an html
source("src/clean_flight_data.R") # Script that loads and cleans up the data
source("src/regression_output.R") # A script that cleans up regression outputs and prints in color or black and white
source("src/center_flight_data.R")
#source("get_warnings.R")

data <- read_flight_data("data/all_flight_data-Winter2020.csv")
data_all <- data[[1]]
data_tested <- data[[2]]

all_data <- data_all %>%
  filter(trial_type != "T2")
all_data <- center_data(all_data)

data_tested <- all_data[all_data$tested == "yes",]
data_tested <- center_data(data_tested)
```

## Counts

### Grouped by Season

```{r echo=FALSE}
Fall = read.csv("/Users/anastasiabernat/Desktop/git_repositories/SBB-dispersal/avbernat_working_on/Dispersal/Autumn_2019/stats/data/full_data3.csv")
mass = Fall %>% filter(mass != 0)
#length(unique(mass$ID))
min30 = Fall %>% filter(set_number <= 30) # where is set002?
min60 = Fall %>% filter(set_number > 30 & set_number <= 52)
min90 = Fall %>% filter(set_number > 52 & set_number <= 71)
unlimited = Fall %>% filter(set_number >= 72)
T1 = data_all %>% filter(trial_type =="T1")
T2 = data_all %>% filter(trial_type =="T2")

n_30 = length(unique(min30$ID))
n_60 = length(unique(min60$ID))
n_90 = length(unique(min90$ID))
n_unlimited = length(unique(unlimited$ID))

season = c("Fall", "Fall", "Fall", "Fall", "Winter", "Winter")
year = c("2019","2019","2019","2019","2020","2020")
dates = c("October 15 to October 23", "October 23 to October 29", "October 30 to November 4", "November 5 to November 8", "February 17 to February 28", "March 3 to March 10")
exp_setup = c("30 min", "60 min", "90 min", "unlimited", "unlimited", "unlimited")
n_tested = c(n_30, n_60, n_90, n_unlimited, nrow(T1), nrow(T2))
wing_morph = c("short and long", "short and long","short and long","long","long","long")

table_season = cbind(season, year,dates, exp_setup, n_tested, wing_morph)
colnames(table_season) <- c("Season", "Year", "Dates", "Experimental Setup", "N Tested", "Wing Morph")

paper_table = kable(table_season) %>%
  kable_styling(bootstrap_options = "striped", "hover", full_width = F)  
paper_table
#save_kable(paper_table, "table2.pdf")
```

## Winter

### Grouped by Sex

```{r echo=FALSE}
num_fem <- nrow(data_all[data_all$sex == "F",])
num_male <- nrow(data_all[data_all$sex == "M",])
num_tested_fem <- nrow(data_tested[data_tested$sex == "F",]) # not a unique value
num_tested_male <- nrow(data_tested[data_tested$sex == "M",]) # not a unique value

table0 <- data.frame("All" = c(num_fem, num_male),
                     "Tested" = c(num_tested_fem, num_tested_male)) 
rownames(table0) <- c("F", "M")

kable(table0) %>%
  kable_styling(bootstrap_options = "striped", "hover", full_width = F)  
```

### Females that Laid Eggs:

```{r echo=FALSE}
all_data <- data[[1]]
unique_num_eggs <- nrow(unique(select(all_data[all_data$sex == "F" & all_data$eggs_b == 1,], ID, eggs_b)))
did_not_lay <- num_tested_fem - unique_num_eggs 
  
table00 <- data.frame(did_not_lay, unique_num_eggs, num_tested_fem, round(unique_num_eggs/num_tested_fem,3))
rownames(table00) <- "Unique Values"
colnames(table00) <- c("Females That Didn't Lay Eggs", "Females That Laid Eggs", "Total Females", "Sample Prop")

kable(table00) %>%
  kable_styling(bootstrap_options = "striped", "hover", full_width = F)  
```

### Grouped by Population

```{r echo=FALSE}
d <- data[[1]][data[[1]]$tested == "yes",]

trial2_sizes <-c()
trial1_sizes <- c()
female_sizes <- c()
male_sizes <- c()
pops <- unique(data_tested$population)
for (pop in pops) {
  nF <- nrow(data_tested[data_tested$population == pop & data_tested$sex == "F",])
  nM <- nrow(data_tested[data_tested$population == pop & data_tested$sex == "M",])
  nT1 <- nrow(data_tested[data_tested$population == pop & data_tested$trial_type == "T1",])
  nT2 <- nrow(data_tested[d$population == pop & d$trial_type == "T2",])
  female_sizes <- c(female_sizes, nF)
  male_sizes <- c(male_sizes, nM)
  trial2_sizes <- c(trial2_sizes, nT2)
  trial1_sizes <- c(trial1_sizes, nT1)
}

table1 <- data.frame(pops, female_sizes, male_sizes, trial1_sizes, trial2_sizes )
colnames(table1) <- c("Population", "Females", "Males", "Trial 1", "Trial 2")

kable(table1) %>%
  kable_styling(bootstrap_options = "striped", "hover", full_width = F)  %>%
  add_header_above(c(" ", "Sex Sample Sizes" = 2, "Trial Sample Sizes" =2)) %>% 
  add_header_above(c("Tested Bugs By Pop, Sex, and Trial Type (Unique)" = 5 ))
```

```{r echo=FALSE}
ndied <- sum(trial1_sizes ) - sum(trial2_sizes )
ndied <- data.frame(ndied)
colnames(ndied) <- "Number of bugs that died between T1 and T2"

kable(ndied) %>%
  kable_styling(bootstrap_options = "striped", "hover", full_width = F) 
```

```{r echo=FALSE}
pop_sample_sizes <- c()
for (pop in pops) {
  n <- nrow(data_tested[data_tested$population == pop,])
  pop_sample_sizes <- c(pop_sample_sizes, n)
}

pop_df <- data.frame(pops, pop_sample_sizes)
colnames(pop_df) <- c("population", "n_pop")

site_sample_sizes <- c()
sites <- unique(data_tested$site)
for (site in sites) {
  n <- nrow(data_tested[data_tested$site == site,])
  site_sample_sizes <- c(site_sample_sizes, n)
}

site_df <- data.frame(sites, site_sample_sizes)
colnames(site_df) <- c("site", "n_site")

coor_df <- unique(select(data_tested, population, site, latitude, longitude)) %>%
  arrange(desc(latitude), population) 

main <- merge(coor_df , site_df,by=c("site"))
table2 <- merge(main , pop_df,by=c("population"))

kable(table2) %>%
  kable_styling(bootstrap_options = "striped", "hover", full_width = F)  %>%
  add_header_above(c(" ", " ", "Coordinates" = 2, "Sample Sizes" = 2 )) %>% 
  add_header_above(c("Tested Bugs By Population and Site" = 6 ))
```

```{r echo=FALSE}
# adding host plant
host_plants = c("K. elegans", "K. elegans", "C. corindum", "C. corindum", 
                "K. elegans", "K. elegans", "K. elegans", "C. corindum",
                "C. corindum", "C. corindum", "C. corindum", "C. corindum",
                "C. corindum", "C. corindum","C. corindum","C. corindum")

table2b = cbind(host_plants, table2)
colnames(table2b)[1] <- c("host plant")
table2b <- table2b[order(-table2b$latitude),]
write.table(table2b, "tables/table1.csv", sep=",", row.names=FALSE)

rownames(table2b) <- NULL
paper_table = kable(table2b) %>%
  kable_styling(bootstrap_options = "striped", "hover", full_width = F)  %>%
  add_header_above(c(" ", " ", " ", "Coordinates" = 2, "Sample Sizes" = 2 )) %>% 
  add_header_above(c("Tested Bugs By Host Plant, Population, and Site" = 7 )) 
paper_table
#save_kable(paper_table,"test.pdf")
```

## Data Stats

### Mass Stats

```{r echo=FALSE}
# calculate number of masses measured by filtering out any bugs whose mass wasn't measured
d <- data_all %>%
  filter(!is.na(mass))
countF <- nrow(d[d$sex == "F",])
countM <- nrow(d[d$sex == "M",])

# calculate means and standard deviations
sex_masses <- t(rbind(tapply(X=data_all$mass, INDEX=data_all$sex, FUN=mean, na.rm=T),
                tapply(X=data_all$mass, INDEX=data_all$sex, FUN=sd, na.rm=T)))

table3 <- data.frame(round(sex_masses,3), c(countF, countM))
colnames(table3) <- c("mean", "sd", "sample size" )

kable(table3) %>%
  kable_styling(bootstrap_options = "striped", "hover", full_width = F)  %>%
  add_header_above(c(" ", "mass (g)" = 2, " " )) 
```

```{r echo=FALSE}
countBV <- nrow(d[d$host_plant == "C. corindum",])
countGRT <- nrow(d[d$host_plant == "K.elegans",])

# calculate means and standard deviations
host_masses <- t(rbind(tapply(X=data_all$mass, INDEX=data_all$host_plant, FUN=mean, na.rm=T),
                tapply(X=data_all$mass, INDEX=data_all$host_plant, FUN=sd, na.rm=T)))

table3 <- data.frame(round(host_masses,3), c(countBV, countGRT))
colnames(table3) <- c("mean", "sd", "sample size" )

kable(table3) %>%
  kable_styling(bootstrap_options = "striped", "hover", full_width = F)  %>%
  add_header_above(c(" ", "mass (g)" = 2, " " )) 
```

```{r echo=FALSE}
# Can add sample sizes here too
table3 <-round(data.frame(cbind(
  tapply(X=data_all$mass, INDEX=list(data_all$sex, data_all$host_plant), FUN=mean, na.rm=T),
  tapply(X=data_all$mass, INDEX=list(data_all$sex, data_all$host_plant), FUN=sd, na.rm=T))),3)

colnames(table3) <- c("meanC", "meanK", "sdC", "sdK")
table3 <- table3[c("meanC", "sdC", "meanK", "sdK")]
colnames(table3) <- c("mean", "sd", "mean", "sd")

kable(table3) %>%
  kable_styling(bootstrap_options = "striped", "hover", full_width = F)  %>%
  add_header_above(c(" ", "C. corindum" = 2, "K. elegans " =2 ))   %>%
  add_header_above(c(" ", "mass (g)" = 4 ))
```

### Morphology Stats

```{r echo=FALSE}
# calculate number of morphology measured by filtering out any bugs whose mass wasn't measured
d <- data_all %>%
  filter(!is.na(thorax))
countF <- nrow(d[d$sex == "F",])
countM <- nrow(d[d$sex == "M",])

# calculate means and standard deviations
thoraxes <- t(rbind(tapply(X=data_all$thorax, INDEX=data_all$sex, FUN=mean, na.rm=T),
      tapply(X=data_all$thorax, INDEX=data_all$sex, FUN=sd, na.rm=T)))

bodies <- t(rbind(tapply(X=data_all$body, INDEX=data_all$sex, FUN=mean, na.rm=T), 
      tapply(X=data_all$body, INDEX=data_all$sex, FUN=sd, na.rm=T)))

wings <- t(rbind(tapply(X=data_all$wing, INDEX=data_all$sex, FUN=mean, na.rm=T), 
      tapply(X=data_all$wing, INDEX=data_all$sex, FUN=sd, na.rm=T)))

#sex_sizes <- c(nrow(data_all[data_all$sex == "F", ]), nrow(data_all[data_all$sex == "M", ]))
sex_sizes <- c(countF, countM)

table4 <- round(data.frame(sex_sizes, thoraxes, bodies, wings),2)
colnames(table4) <- c("sample size", "mean", "sd", "mean", "sd", "mean", "sd" )

kable(table4) %>%
  kable_styling(bootstrap_options = "striped", "hover", full_width = F)  %>%
  add_header_above(c(" ", " ", "thorax (mm) " = 2, "body (mm)" = 2, "wing (mm)" = 2 )) %>% 
  add_header_above(c(" ", " ", "All Bugs" = 6 ))
```

```{r echo=FALSE}
# calculate number of morphology measured by filtering out any bugs whose mass wasn't measured
d <- data_tested %>%
  filter(!is.na(thorax))
countF <- nrow(d[d$sex == "F",])
countM <- nrow(d[d$sex == "M",])

# calculate means and standard deviations
thoraxes <- t(rbind(tapply(X=data_tested$thorax, INDEX=data_tested$sex, FUN=mean, na.rm=T),
      tapply(X=data_tested$thorax, INDEX=data_tested$sex, FUN=sd, na.rm=T)))

bodies <- t(rbind(tapply(X=data_tested$body, INDEX=data_tested$sex, FUN=mean, na.rm=T), 
      tapply(X=data_tested$body, INDEX=data_tested$sex, FUN=sd, na.rm=T)))

wings <- t(rbind(tapply(X=data_tested$wing, INDEX=data_tested$sex, FUN=mean, na.rm=T), 
      tapply(X=data_tested$wing, INDEX=data_tested$sex, FUN=sd, na.rm=T)))

#sex_sizes <- c(nrow(data_tested[data_tested$sex == "F", ]), nrow(data_tested[data_tested$sex == "M", ]))
sex_sizes <- c(countF, countM)

table5 <- round(data.frame(sex_sizes, thoraxes, bodies, wings),2)
colnames(table5) <- c("sample size", "mean", "sd", "mean", "sd", "mean", "sd" )

kable(table5) %>%
  kable_styling(bootstrap_options = "striped", "hover", full_width = F)  %>%
  add_header_above(c(" ", " ", "thorax (mm) " = 2, "body (mm)" = 2, "wing (mm)" = 2 )) %>% 
  add_header_above(c(" ", " ", "Tested Bugs" = 6 ))
```

### Flight Response Stats

```{r echo=FALSE}
data_tested <- data[[2]]
data_T1 <- data_tested[data_tested$trial_type == "T1",]
data_T2 <- data_tested[data_tested$trial_type == "T2",]

T1flew <- cbind(mean(data_T1$flew_b), sd(data_T1$flew_b), nrow(data_T1))
T2flew <- cbind(mean(data_T2$flew_b), sd(data_T2$flew_b), nrow(data_T2))

table6 <- round(data.frame(rbind(T1flew, T2flew)), 2)
colnames(table6) <- c("prop flew", "sd", "sample size")
rownames(table6) <- c("Trial 1", "Trial 2")

kable(table6) %>%
  kable_styling(bootstrap_options = "striped", "hover", full_width = F)  
```

```{r echo=FALSE}
sexes_flew <- t(rbind(tapply(X=data_T1$flew_b, INDEX=data_T1$sex, FUN=mean, na.rm=T),
                tapply(X=data_T1$flew_b, INDEX=data_T1$sex, FUN=sd, na.rm=T),
                c(nrow(data_T1[data_T1$sex == "F", ]), nrow(data_T1[data_T1$sex == "M", ])),
                tapply(X=data_T2$flew_b, INDEX=data_T2$sex, FUN=mean, na.rm=T),
                tapply(X=data_T2$flew_b, INDEX=data_T2$sex, FUN=sd, na.rm=T),
                c(nrow(data_T2[data_T2$sex == "F", ]), nrow(data_T2[data_T2$sex == "M", ]))
                ))

table7 <- round(data.frame(sexes_flew),2)
colnames(table7 ) <- c("prop flew", "sd", "sample size", "prop flew", "sd", "sample size" )

kable(table7) %>%
  kable_styling(bootstrap_options = "striped", "hover", full_width = F)  %>%
  add_header_above(c(" ", "Trial 1 " = 3, "Trial 2" = 3 )) 
```

### Distance Stats

```{r echo=FALSE}
sexes_distance <- t(rbind(tapply(X=data_T1$distance, INDEX=data_T1$sex, FUN=mean, na.rm=T),
                tapply(X=data_T1$distance, INDEX=data_T1$sex, FUN=sd, na.rm=T),
                c(nrow(data_T1[data_T1$sex == "F", ]), nrow(data_T1[data_T1$sex == "M", ])),
                tapply(X=data_T2$distance, INDEX=data_T2$sex, FUN=mean, na.rm=T),
                tapply(X=data_T2$distance, INDEX=data_T2$sex, FUN=sd, na.rm=T),
                c(nrow(data_T2[data_T2$sex == "F", ]), nrow(data_T2[data_T2$sex == "M", ]))
                ))

table8 <- round(data.frame(sexes_distance),2)
colnames(table8) <- c("mean", "sd", "sample size", "mean", "sd", "sample size" )

kable(table8) %>%
  kable_styling(bootstrap_options = "striped", "hover", full_width = F)  %>%
  add_header_above(c(" ", "Trial 1 " = 3, "Trial 2" = 3 )) %>%
  add_header_above(c(" ", "Distances Flew (m)" = 6))
```

```{r echo=FALSE}
flight_type_distance <- t(rbind(
  tapply(X=data_T1$distance, INDEX=data_T1$flight_type, FUN=mean, na.rm=T),
  tapply(X=data_T1$distance, INDEX=data_T1$flight_type, FUN=sd, na.rm=T),
  with(data_T1, tapply(filename, flight_type, function(X) length(unique(X)))),
  tapply(X=data_T2$distance, INDEX=data_T2$flight_type, FUN=mean, na.rm=T),
  tapply(X=data_T2$distance, INDEX=data_T2$flight_type, FUN=sd, na.rm=T),
  with(data_T2, tapply(filename, flight_type, function(X) length(unique(X))))
  ))

table9 <- round(data.frame(flight_type_distance),2)
colnames(table9) <- c("mean", "sd", "sample size", "mean", "sd", "sample size" )

kable(table9) %>%
  kable_styling(bootstrap_options = "striped", "hover", full_width = F)  %>%
  add_header_above(c(" ", "Trial 1 " = 3, "Trial 2" = 3 )) %>%
  add_header_above(c(" ", "Distances Flew (m)" = 6))
```

```{r echo=FALSE}
data_T1$flight_type <- as.character(data_T1$flight_type)
data_T2$flight_type <- as.character(data_T2$flight_type)
data_T1$flight_type[data_T1$flight_type == "CB" | data_T1$flight_type == "BC"] <- "C"
data_T2$flight_type[data_T2$flight_type == "CB" | data_T2$flight_type == "BC"] <- "C"

flight_type_distance2 <- t(rbind(
  tapply(X=data_T1$distance, INDEX=data_T1$flight_type, FUN=mean, na.rm=T),
  tapply(X=data_T1$distance, INDEX=data_T1$flight_type, FUN=sd, na.rm=T),
  with(data_T1, tapply(filename, flight_type, function(X) length(unique(X)))),
  tapply(X=data_T2$distance, INDEX=data_T2$flight_type, FUN=mean, na.rm=T),
  tapply(X=data_T2$distance, INDEX=data_T2$flight_type, FUN=sd, na.rm=T),
  with(data_T2, tapply(filename, flight_type, function(X) length(unique(X))))
  ))

table10 <- round(data.frame(flight_type_distance2),2)
colnames(table10) <- c("mean", "sd", "sample size", "mean", "sd", "sample size" )

kable(table10) %>%
  kable_styling(bootstrap_options = "striped", "hover", full_width = F)  %>%
  add_header_above(c(" ", "Trial 1 " = 3, "Trial 2" = 3 )) %>%
  add_header_above(c(" ", "Distances Flew (m)" = 6))
```

### Speed Stats

```{r echo=FALSE}
data_tested <- data[[2]]
data_T1 <- data_tested[data_tested$trial_type == "T1",]
data_T2 <- data_tested[data_tested$trial_type == "T2",]

sexes_speed <- t(rbind(tapply(X=data_T1$average_speed, INDEX=data_T1$sex, FUN=mean, na.rm=T),
                tapply(X=data_T1$average_speed, INDEX=data_T1$sex, FUN=sd, na.rm=T),
                c(nrow(data_T1[data_T1$sex == "F", ]), nrow(data_T1[data_T1$sex == "M", ])),
                tapply(X=data_T2$average_speed, INDEX=data_T2$sex, FUN=mean, na.rm=T),
                tapply(X=data_T2$average_speed, INDEX=data_T2$sex, FUN=sd, na.rm=T),
                c(nrow(data_T2[data_T2$sex == "F", ]), nrow(data_T2[data_T2$sex == "M", ]))
                ))

table11 <- round(data.frame(sexes_speed),2)
colnames(table11) <- c("mean", "sd", "sample size", "mean", "sd", "sample size" )

kable(table11) %>%
  kable_styling(bootstrap_options = "striped", "hover", full_width = F)  %>%
  add_header_above(c(" ", "Trial 1 " = 3, "Trial 2" = 3 )) %>%
  add_header_above(c(" ", "Average Speed Flew (m/s)" = 6))
```

```{r echo=FALSE}
flight_type_speed <- t(rbind(
  tapply(X=data_T1$average_speed, INDEX=data_T1$flight_type, FUN=mean, na.rm=T),
  tapply(X=data_T1$average_speed, INDEX=data_T1$flight_type, FUN=sd, na.rm=T),
  with(data_T1, tapply(filename, flight_type, function(X) length(unique(X)))),
  tapply(X=data_T2$average_speed, INDEX=data_T2$flight_type, FUN=mean, na.rm=T),
  tapply(X=data_T2$average_speed, INDEX=data_T2$flight_type, FUN=sd, na.rm=T),
  with(data_T2, tapply(filename, flight_type, function(X) length(unique(X))))
  ))

table12 <- round(data.frame(flight_type_speed),2)
colnames(table12) <- c("mean", "sd", "sample size", "mean", "sd", "sample size" )

kable(table12) %>%
  kable_styling(bootstrap_options = "striped", "hover", full_width = F)  %>%
  add_header_above(c(" ", "Trial 1 " = 3, "Trial 2" = 3 )) %>%
  add_header_above(c(" ", "Average Speed Flew (m/s)" = 6))
```

```{r echo=FALSE}
data_T1$flight_type <- as.character(data_T1$flight_type)
data_T2$flight_type <- as.character(data_T2$flight_type)
data_T1$flight_type[data_T1$flight_type == "CB" | data_T1$flight_type == "BC"] <- "C"
data_T2$flight_type[data_T2$flight_type == "CB" | data_T2$flight_type == "BC"] <- "C"

flight_type_distance2 <- t(rbind(
  tapply(X=data_T1$average_speed, INDEX=data_T1$flight_type, FUN=mean, na.rm=T),
  tapply(X=data_T1$average_speed, INDEX=data_T1$flight_type, FUN=sd, na.rm=T),
  with(data_T1, tapply(filename, flight_type, function(X) length(unique(X)))),
  tapply(X=data_T2$average_speed, INDEX=data_T2$flight_type, FUN=mean, na.rm=T),
  tapply(X=data_T2$average_speed, INDEX=data_T2$flight_type, FUN=sd, na.rm=T),
  with(data_T2, tapply(filename, flight_type, function(X) length(unique(X))))
  ))

table13 <- round(data.frame(flight_type_distance2),2)
colnames(table13) <- c("mean", "sd", "sample size", "mean", "sd", "sample size" )

kable(table13) %>%
  kable_styling(bootstrap_options = "striped", "hover", full_width = F)  %>%
  add_header_above(c(" ", "Trial 1 " = 3, "Trial 2" = 3 )) %>%
  add_header_above(c(" ", "Average Speed Flew (m/s)" = 6))
```




