import os
import csv
import numpy as np
import matplotlib
import shutil

from os import path
from matplotlib import pyplot as plt
from matplotlib import style

style.use('ggplot')

#******************************************************************************
# Generates a graph or multiple graphs in specified directory. Inputs are text
# files generated by the flight_analysis python script with the first column
# representing time (seconds from the start) and the second column representing
# speed in m/s. the x-axis is time while the y-axis is speed (m/s). The output
# is a graph saved as a .png in a specified directory or folder. 
#******************************************************************************

path = "/Users/anastasiabernat/Desktop/Flight Analyses 5/"
dir_list = sorted(os.listdir(path))
for filename in dir_list:
    if filename.startswith("."):
        continue
    filepath = r"/Users/anastasiabernat/Desktop/Flight Analyses 5/" + str(filename)
    input_file = open(filepath, mode="r", encoding='latin-1')

    x = []
    y = []
    for row in input_file:
        split = row.split(',')
        x.append(float(split[0]))
        y.append(float(split[1]))

    if x == [0.0] and y == [0.0]:
        continue

    del x[-1]
    del y[-1]

    plt.plot(x,y, 'c', linewidth = 0.8)
    plt.title('Flight Data' + str(' ') + str(filename))
    plt.ylabel('Speed (m/s)')
    plt.xlabel('Seconds from start')
#    plt.grid(True, color = 'k')
#    plt.show()

    input_file.close()

    outpath = r'/Users/anastasiabernat/Desktop/Graphs6/'
    output_filename = str(filename).split("_")[-1].replace(".txt", "") + '.png'
    concatenated_path = os.path.join(outpath, output_filename)

    plt.savefig(concatenated_path, dpi=300, bbox_inches='tight')
    plt.clf()

#plt.close()
