---
title: "Untitled"
author: "Anastasia Bernat"
date: "10/6/2021"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
dir = "/Users/anastasiabernat/Desktop/git_repositories/SBB-dispersal/avbernat_working_on/Dispersal/Summer_2021/windaq_processing/data/"
setwd(dir)

knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# cleaning and checking of the data input
prelims = read.csv(paste0(dir,"prelim_extreme_data.csv"), header=TRUE) #, stringsAsFactors = TRUE)

masterlist = read.csv(paste0(dir,"masterlist.csv"), header=TRUE) #, stringsAsFactors = TRUE)
```

```{r}
prelims
```

```{r}
prelims = prelims %>%
  filter(ID != "ID")
prelims = prelims[,-c(13)]
```

```{r}
unique(prelims$test_date)
```


```{r}
merged.data <- merge(masterlist, prelims, by="ID")
```

```{r}
unique(prelims$test_date)
```

```{r}
for (i in 1:nrow(merged.data)){
  if (merged.data[i,"date_died"] != merged.data[i,"test_date"]) {
    if (merged.data[i,"date_died"] == "?") {
      print(c(merged.data[i,"ID"], merged.data[i,"date_died"], 
              merged.data[i-1,"test_date"], merged.data[i+1,"test_date"], merged.data[i,"died."]))
    }
  }
}

ids = which(masterlist$date_died == "?")
```

```{r}
# bugs with questions marks most likely died before the the first trials ran on 9.8.21
# so assume that the bugs died on 9.7.21 and assign that death date to the masterlist

question_mark_date = "9.7.21"
note = "death date assumption"


colnames(masterlist) = c(colnames(masterlist)[1:7], "S_wing", "notes")
#masterlist[masterlist$notes == "",]$notes = note


masterlist[masterlist$date_died == "?",]$date_died = question_mark_date
masterlist[masterlist$died == "",]$notes = note
masterlist[masterlist$died == "",]$died = "Y"

masterlist
```

```{r}
which(masterlist$date_died == "?")
```


```{r}
write.csv(masterlist, paste0(dir, "masterlist-clean.csv"), row.names = FALSE)
```

