---
title: "Manuscript Figures"
author: "Anastasia Bernat"
geometry: margin=2cm
output:
  pdf_document:
    includes: null
    toc: no
    toc_depth: 3
    number_sections: true
  html_document:
    toc: no
    toc_depth: '3'
    df_print: paged
line-height: 1.5
fontsize: 11pt
classoption: a4paper
language: en
---

```{r setup, include=FALSE}
rm(list = ls())

# set working directory
dir = "~/Desktop/git_repositories/SBB-dispersal/avbernat/"
setwd(dir)

knitr::opts_knit$set(root.dir = dir)
knitr::opts_chunk$set(echo = TRUE)
```


```{r reading-libraries, message=FALSE, echo=FALSE}
## Read Libraries

library(lme4)      # fit regressions 
library(dplyr)     # data manipulation 
library(ggformula) # ggplot plotting
library(cowplot)   # ggplot helper functions to arrange multi-panel figures
library(binom)     # binomial confidence intervals

library(rethinking) # Bayesian data analysis and plotting
library(popbio)     # logistic regression plotting
```



```{r sourcing-scripts, message=FALSE, echo=FALSE}
## Read Source Files

source_path = paste0(dir,"/Rsrc/")

script_names = c("clean_morph_data.R",   # 1 function: read_morph_data() 
                 "clean_flight_data.R",   # 1 function: clean_flight_data()
                 "center_flight_data.R",  # 1 function: center_data()
                 "unique_flight_data.R",  # 1 function: create_delta_data()
                 "clean_flight_data-Fall.R",  # 1 function: clean_flight_data.Fall()
                 "unique_flight_data-Fall.R", # 1 function: create_delta_data.Fall()
                 "remove_torn_wings.R",  # 1 function: remove_torn_wings()
                 "compare_models.R",     # 1 function: model_comparisonsAIC()
                 "get_Akaike_weights.R") # 1 function: get_model_probs()

for (script in script_names) { 
  path = paste0(source_path, script)
  source(path) 
}
```

```{r reading-data, echo=FALSE, results='hide'}
## Read the Data
datapath = paste0(dir,"All_Morphology/stats/data/allmorphology05.18.21.csv")
data_list = read_morph_data(datapath)

raw_data = data_list[[1]]
data_long = data_list[[2]] # long-wing bugs with wing-to-body value only

data_long = remove_torn_wings(data_long)
```

## Figure 1 

```{r echo=FALSE}
# repeating plot features
customPlot = list(geom_bar(position='stack', color="black", width=0.7),
                  theme_classic(),
                  theme(axis.text.y = element_text(size=11),
                        axis.text.x = element_text(size=11, angle = 45, hjust = 1.1),
                        axis.title = element_text(size=17)),
                  theme(axis.title.x = element_text(size=13,vjust = -3)),
                  theme(axis.title.y = element_text(size=13, vjust = 4)),
                  theme(plot.margin=unit(c(1,1,1.1,1.2),"cm")),
                  theme(legend.title = element_text(size=11, face="italic"),
                         legend.text = element_text(size = 11, face="italic"))
                  )
```

```{r sexes-barplot, fig.height=1.9, fig.width=2.7, echo=FALSE}
raw_data$pophost = as.factor(raw_data$pophost)
raw_data$pophost = relevel(raw_data$pophost, "K. elegans")
p2 = ggplot(data=subset(raw_data, !is.na(datetime)), aes(x=datetime, fill=pophost)) + 
  labs(
       fill="Host Plant", x="Field Collection Date", y="Number of Bugs Collected") +
  scale_fill_manual(values=c("#68b054", "#56B4E9")) + # #3a8c1c
  customPlot + 
  theme(plot.title = element_text(hjust = 0.5)) +   
  theme(plot.margin=unit(c(1,0.15,1,0.85), "cm"))
p2
```

```{r warning=FALSE}
data_path = paste0(dir,"/Dispersal/Winter_2020/stats/data/all_flight_data-Winter2020.csv")

data = read_flight_data(data_path) # centers each subset of data
data_all = data[[1]]               # full dataset
data_tested = data[[2]]            # subset of data_all, contains only bugs flight tested

# create the unique dataset
winter_data = create_delta_data(data_tested, remove_bugs_tested_once = FALSE) 
```

```{r warning=FALSE}
data_path = paste0(dir,"/Dispersal/Winter_2020/stats/data/full_data-Fall2019.csv")
data_tested = clean_flight_data.Fall(data_path)

# fall_data = create_delta_data.Fall(data_tested) # removes those not tested twice

fall_data <- data_tested %>%
  group_by(ID, sex, population, site, host_plant, latitude, longitude, 
             host_c, sex_c, w_morph_c, lat_c, sym_dist) %>%
  summarise_all(funs(list(na.omit(.))))
```

```{r sexes-barplot, fig.height=1.5, fig.width=1.3, echo=FALSE}
#subdata = raw_data[raw_data$date == "October/2019" | raw_data$date == "February/2020",]

fall_data$datetime = unique(raw_data$datetime)[8]
winter_data$datetime = unique(raw_data$datetime)[7]
sub_data = rbind(fall_data[,c("host_plant", "datetime")],
                 winter_data[,c("host_plant", "datetime")])

sub_data$host_plant = as.factor(sub_data$host_plant)
sub_data$host_plant = relevel(sub_data$host_plant, "K. elegans")


p3 = ggplot(data=subset(sub_data, !is.na(datetime)), aes(x=datetime, fill=host_plant)) + 
  labs(
       fill="Host Plant", x=" ", y=" ") +
  scale_fill_manual(values=c("#68b054", "#56B4E9")) + # #3a8c1c
  customPlot + 
  theme(plot.title = element_text(hjust = 0.5)) +   
  theme(plot.margin=unit(c(1,0.15,1,0.85), "cm")) +
  theme(axis.text.y = element_text(size=15),
                        axis.text.x = element_text(size=15, angle = 45, hjust = 1.1),
                        axis.title = element_text(size=17))
p3
```



