---
title: "All Morphology: Wing LOESS"
author: "Anastasia Bernat"
date: "4/8/2021"
output:
  html_document:
    theme: united
---

```{r setup, include=FALSE}
rm(list=ls())
library(ggformula)
library(splines)
library(gridExtra) #grid.arrange()
library(ggpmisc) #stat_fit_glance

knitr::opts_chunk$set(echo = TRUE)
```

## Cleaning Data and Sourcing Scripts

```{r}
source_path = "~/Desktop/git_repositories/SBB-dispersal/avbernat_working_on/Rsrc/"

script_names = c("compare_models.R","regression_output.R", "clean_morph_data.R", "AICprobabilities.R")

for (script in script_names) { 
  path = paste0(source_path, script)
  source(path) 
}
```

### Read the data

```{r warning=FALSE}
data_list <- read_morph_data("data/allmorphology9.21.20-clean.csv")
raw_data = data_list[[1]]
data_long = data_list[[2]]
```

## Wing2Body 

```{r}
COL1 = rgb(1,0.3,0,0.7)
COL2 = rgb(0,0.8,1,0.7)

SE = function(x){sd(x)/sqrt(length(x))}
w2b_summary<-aggregate(wing2body~sex*pophost*dates, data=data_long, FUN=mean)
w2b_summary$se<-aggregate(wing2body~sex*pophost*dates, data=data_long,
                          FUN=SE)$wing2body

w2b_summary$color <- COL1
w2b_summary$color[w2b_summary$pophost=="K.elegans"] <- COL2

#jitter slightly
jitter = runif(n=nrow(w2b_summary), min=-0.5, max=0.5)
w2b_summary$dates <- w2b_summary$dates + jitter
```


Loess Regression: (base R) http://r-statistics.co/Loess-Regression-With-R.html

```{r}
# define function that returns the SSE
calcSSE <- function(x){
  loessMod <- try(loess(wing2body ~ index, data=w2b_summary, span=x), silent=T)
  res <- try(loessMod$residuals, silent=T)
  if(class(res)!="try-error"){
    if((sum(res, na.rm=T) > 0)){
      sse <- sum(res^2)  
    }
  }else{
    sse <- 99999
  }
  return(sse)
}

# Run optim to find span that gives min SSE, starting at 0.5
#optim(par=c(0.25), calcSSE, method="SANN")
#optim(par=c(1), calcSSE, method="SANN")
```

```{r}
w2b_summary$index = 1:nrow(w2b_summary)
loessMod20 <- loess(wing2body ~ index, data=w2b_summary, span=0.20, degree=2) # 20% smoothing span
loessMod40 <- loess(wing2body ~ index, data=w2b_summary, span=0.40, degree=2) # 40% smoothing span
loessMod60 <- loess(wing2body ~ index, data=w2b_summary, span=0.60, degree=2) # 60% smoothing span
loessMod80 <- loess(wing2body ~ index, data=w2b_summary, span=0.80, degree=2) # 80% smoothing span

smoothed20 <- predict(loessMod20) 
smoothed40 <- predict(loessMod40) 
smoothed60 <- predict(loessMod60)
smoothed80 <- predict(loessMod80) 
# Plot it
plot(w2b_summary$wing2body, x=w2b_summary$dates, type="p", main="Loess Smoothing and Prediction", xlab="months since start", ylab="wing:body")
#lines(smoothed20, x=w2b_summary$dates, col="red")
#lines(smoothed40, x=w2b_summary$dates, col="green")
lines(smoothed60, x=w2b_summary$dates, col="blue")
#lines(smoothed80, x=w2b_summary$dates, col="orange")
#?lowess
```

lmFC <- lm(wing2body ~ months_since_start, data=dfFC)
predFC <- data.frame(wing2body = predict(lmFC, dfFC), months_since_start=dfFC$months_since_start)

```{r}
df = w2b_summary
dfF = df[df$sex=="F",]
dfM = df[df$sex=="M",]

dfFC = df[df$sex=="F" & df$pophost =="C.corindum",]
dfFK = df[df$sex=="F" & df$pophost =="K.elegans",]

# general plotting features
xlab_dates = na.omit(sort(unique(data_long$dates))[-2])
host_colors_shade = c("turquoise3", "green")
host_colors_pts = c("turquoise3", "springgreen4")
```

```{r fig.width=4.7, fig.height=2.3}
# create a LOESS plot
# females
p1 = ggplot() + 
  ggtitle("Females") + xlab("Year") + ylab("Wing-to-Body Ratio") +
  geom_vline(xintercept = xlab_dates, color="gainsboro") + 
  geom_smooth(data=dfF, method="loess", 
              mapping = aes(x = dates, y = wing2body, colour=pophost, fill=pophost)) + 
  geom_point(data=dfF, mapping = aes(x = dates, y = wing2body, colour=pophost)) +
  ylim(0.70, 0.76) 

p1 = p1 + guides(fill = guide_legend(reverse = TRUE)) + theme_classic() +
  theme(axis.text=element_text(size=13),
        axis.title=element_text(size=16), 
        plot.title=element_text(size=18, face="italic")) + guides(color = FALSE)  + scale_linetype(guide = FALSE) +
  theme(legend.key = element_rect(fill = "white", color = NA), 
        legend.key.size = unit(0.5, "cm"),
        legend.key.width = unit(0.5,"cm")) + 
  scale_fill_manual(values = host_colors_shade, labels=c("C. corindum", "K. elegans")) + 
  labs(fill = "Host Plant") + theme(legend.title = element_text(size = 14),
                                    legend.text = element_text(size = 13, face="italic")) +
  scale_color_manual(values=host_colors_pts) + theme(legend.position = c(0.2, 0.88)) + theme(legend.title = element_blank())

# males
p2 = ggplot() + 
  ggtitle("Males") + xlab("Year") + ylab(" ") +
  geom_vline(xintercept = xlab_dates, color="gainsboro") + 
  geom_smooth(data=dfM, method="loess", 
              mapping = aes(x = dates, y = wing2body, colour=pophost, fill=pophost)) + 
  geom_point(data=dfM, mapping = aes(x = dates, y = wing2body, colour=pophost)) + ylim(0.70, 0.76)

p2 = p2 + guides(fill = guide_legend(reverse = TRUE)) + theme_classic() +
  theme(axis.text=element_text(size=13),
        axis.title=element_text(size=16), 
        plot.title=element_text(size=18, face="italic")) + guides(color = FALSE)  + scale_linetype(guide = FALSE) +
  theme(legend.key = element_rect(fill = "white", color = NA), 
        legend.key.size = unit(0.5, "cm"),
        legend.key.width = unit(0.5,"cm")) + 
  scale_fill_manual(values = host_colors_shade) + 
  labs(fill = "Host Plant") + theme(legend.title = element_text(size = 14),
                                    legend.text = element_text(size = 13, face="italic")) +
  scale_color_manual(values=host_colors_pts) + theme(legend.position = "none")

grid.arrange(p1, p2, ncol=2)
```
Now do it by season because that's more interesting...

```{r}
w2b_summary<-aggregate(wing2body~sex*pophost*month_of_year, data=data_long, FUN=mean)
df = w2b_summary
dfF = df[df$sex=="F",]
dfM = df[df$sex=="M",]

xlab_dates = na.omit(sort(unique(data_long$month_of_year)))
xlab_months = xlab_dates[c(-2,-5)]
month_labs <- c("Feb", "May", "Aug", "Oct", "Dec")

sex_colors_shade = c("brown1", "sienna4")
sex_colors_pts = c("brown1", "grey27")
```

```{r}
mlinear = glm(wing2body ~ month_of_year, data=df, family=gaussian)
round(summary(mlinear)$coeff[[8]],3) # significant for all (but only with K.elegans)
pvalue = paste0("p=",round(summary(mlinear)$coeff[[8]],3), "*")
```

```{r}
ggplot() + 
  ggtitle("Host Plant") + xlab("Month") + ylab("Wing-to-Body Ratio") +                              # title and labels
  geom_vline(xintercept = xlab_dates, color="gainsboro") +                                          # add grey lines for the each collection date
  geom_smooth(data=w2b_summary, method="glm", se=FALSE, linetype = "dashed",                        # GLM regression and pvalue
              mapping = aes(x = month_of_year, y = wing2body), colour="black", lwd=0.5) + 
  annotate(geom="text", x=6.2, y=0.72, label=pvalue, color="black") + 
  geom_smooth(data=w2b_summary, method="loess",                                                     # LOESS regression
              mapping = aes(x = month_of_year, y = wing2body, colour=pophost, fill=pophost)) + 
  geom_point(data=w2b_summary, mapping = aes(x = month_of_year, y = wing2body, colour=pophost)) +   # data points and yaxis value range
  ylim(0.70, 0.76) +
  
  theme_classic() + 
  theme(axis.text=element_text(size=13),
        axis.title=element_text(size=16), 
        plot.title=element_text(size=18, face="italic")) +
  theme(legend.position = c(0.2, 0.9)) +
  theme(legend.key = element_rect(fill = "white", color = NA), 
        legend.key.size = unit(0.5, "cm"),
        legend.key.width = unit(0.5,"cm"))


+ guides(fill = guide_legend(reverse = TRUE)) + theme_classic() +
  theme(axis.text=element_text(size=13),
        axis.title=element_text(size=16), 
        plot.title=element_text(size=18, face="italic"))  + 
  scale_linetype(guide = FALSE) +
  theme(legend.key = element_rect(fill = "white", color = NA), 
        legend.key.size = unit(0.5, "cm"),
        legend.key.width = unit(0.5,"cm")) + 
  scale_fill_manual(values = host_colors_shade, labels=c("C. corindum", "K. elegans")) + 
  labs(fill = " ") + theme(legend.title = element_text(size = 14),
                                    legend.text = element_text(size = 13, face="italic")) +
  scale_color_manual(values=host_colors_pts) + theme(legend.position = c(0.2, 0.9))  +
  scale_x_continuous(breaks=xlab_months, labels= month_labs) 
```

```{r fig.width=4.7, fig.height=2.3}
p5 = ggplot() + 
  ggtitle("Host Plant") + xlab("Month") + ylab("Wing-to-Body Ratio") +
  geom_vline(xintercept = xlab_dates, color="gainsboro") + 
  geom_smooth(data=w2b_summary, method="lm", se=FALSE, linetype = "dashed",
              mapping = aes(x = month_of_year, y = wing2body), colour="black", lwd=0.5) + 
  annotate(geom="text", x=6.2, y=0.72, label=pvalue,
              color="black") +
  geom_smooth(data=w2b_summary, method="loess", 
              mapping = aes(x = month_of_year, y = wing2body, colour=pophost, fill=pophost)) + 
  geom_point(data=w2b_summary, mapping = aes(x = month_of_year, y = wing2body, colour=pophost)) + ylim(0.70, 0.76)

p5 = p5 + guides(fill = guide_legend(reverse = TRUE)) + theme_classic() +
  theme(axis.text=element_text(size=13),
        axis.title=element_text(size=16), 
        plot.title=element_text(size=18, face="italic")) + guides(color = FALSE)  + 
  scale_linetype(guide = FALSE) +
  theme(legend.key = element_rect(fill = "white", color = NA), 
        legend.key.size = unit(0.5, "cm"),
        legend.key.width = unit(0.5,"cm")) + 
  scale_fill_manual(values = host_colors_shade, labels=c("C. corindum", "K. elegans")) + 
  labs(fill = " ") + theme(legend.title = element_text(size = 14),
                                    legend.text = element_text(size = 13, face="italic")) +
  scale_color_manual(values=host_colors_pts) + theme(legend.position = c(0.2, 0.9))  +
  scale_x_continuous(breaks=xlab_months, labels= month_labs) 

p6 = ggplot() + 
  ggtitle("Sex") + xlab("Month") + ylab(" ") +
  geom_vline(xintercept = xlab_dates, color="gainsboro") + 
  geom_smooth(data=w2b_summary, method="lm", se=FALSE, linetype = "dashed",
              mapping = aes(x = month_of_year, y = wing2body), colour="black", lwd=0.5) + 
  annotate(geom="text", x=6, y=0.72, label=pvalue,
              color="black") +
  geom_smooth(data=w2b_summary, method="loess", 
              mapping = aes(x = month_of_year, y = wing2body, colour=sex, fill=sex)) + 
  geom_point(data=w2b_summary, mapping = aes(x = month_of_year, y = wing2body, colour=sex)) + ylim(0.70, 0.76)
p6 = p6 + guides(fill = guide_legend(reverse = TRUE)) + theme_classic() +
  theme(axis.text=element_text(size=13),
        axis.title=element_text(size=16), 
        plot.title=element_text(size=18, face="italic")) + guides(color = FALSE)  + scale_linetype(guide = FALSE) +
  theme(legend.key = element_rect(fill = "white", color = NA), 
        legend.key.size = unit(0.5, "cm"),
        legend.key.width = unit(0.5,"cm")) + 
  scale_fill_manual(values = sex_colors_shade, labels=c("Females", "Males")) + 
  labs(fill = "Sex") + theme(legend.title = element_text(size = 14),
                                    legend.text = element_text(size = 13, face="italic")) +
  scale_color_manual(values=sex_colors_pts) + theme(legend.position = c(0.2, 0.9)) + theme(legend.title = element_blank()) +
  scale_x_continuous(breaks=xlab_months, labels= month_labs)

grid.arrange(p5, p6,ncol=2)
```

```{r fig.width=4.7, fig.height=2.3}
# create a LOESS plot
# females

p3 = ggplot() + 
  ggtitle("Females") + xlab("Month") + ylab("Wing-to-Body Ratio") +
  geom_vline(xintercept = xlab_dates, color="gainsboro") + 
  geom_smooth(data=dfF, method="lm", se=FALSE, linetype = "dashed",
              mapping = aes(x = month_of_year, y = wing2body, colour = pophost)) +
  geom_smooth(data=dfF, method="loess", 
              mapping = aes(x = month_of_year, y = wing2body, colour=pophost, fill=pophost)) + 
  geom_point(data=dfF, mapping = aes(x = month_of_year, y = wing2body, colour=pophost)) +
  ylim(0.70, 0.76)

p3 = p3 + guides(fill = guide_legend(reverse = TRUE)) + theme_classic() +
  theme(axis.text=element_text(size=13),
        axis.title=element_text(size=16), 
        plot.title=element_text(size=18, face="italic")) + guides(color = FALSE)  + scale_linetype(guide = FALSE) +
  theme(legend.key = element_rect(fill = "white", color = NA), 
        legend.key.size = unit(0.5, "cm"),
        legend.key.width = unit(0.5,"cm")) + 
  scale_fill_manual(values = host_colors_shade, labels=c("C. corindum", "K. elegans")) + 
  labs(fill = "Host Plant") + theme(legend.title = element_text(size = 14),
                                    legend.text = element_text(size = 13, face="italic")) +
  scale_color_manual(values=host_colors_pts) + theme(legend.position = c(0.2, 0.95)) + theme(legend.title = element_blank()) +
  scale_x_continuous(breaks=xlab_months, labels= month_labs)

# males
p4 = ggplot() + 
  ggtitle("Males") + xlab("Month") + ylab(" ") +
  ylim(0.70, 0.76) +
  geom_vline(xintercept = xlab_dates, color="gainsboro") +
  geom_smooth(data=dfM, method="lm", se=FALSE, linetype = "dashed",
              mapping = aes(x = month_of_year, y = wing2body, colour = pophost)) +
  geom_smooth(data=dfM, method="loess", 
              mapping = aes(x = month_of_year, y = wing2body, colour=pophost, fill=pophost)) + 
  geom_point(data=dfM, mapping = aes(x = month_of_year, y = wing2body, colour=pophost)) 

p4 = p4 + guides(fill = guide_legend(reverse = TRUE)) + theme_classic() +
  theme(axis.text=element_text(size=13),
        axis.title=element_text(size=16), 
        plot.title=element_text(size=18, face="italic")) + guides(color = FALSE)  + scale_linetype(guide = FALSE) +
  theme(legend.key = element_rect(fill = "white", color = NA), 
        legend.key.size = unit(0.5, "cm"),
        legend.key.width = unit(0.5,"cm")) + 
  scale_fill_manual(values = host_colors_shade) + 
  labs(fill = "Host Plant") + theme(legend.title = element_text(size = 14),
                                    legend.text = element_text(size = 13, face="italic")) +
  scale_color_manual(values=host_colors_pts) + theme(legend.position = "none") +
  scale_x_continuous(breaks=xlab_months, labels= month_labs) 

grid.arrange(p3, p4, ncol=2)
```

```{r}
# extract the LOESS
ggplot_build(p3)$data[[2]]
ggplot_build(p4)$data[[2]]

# these calculations give you similar tables. Here is an example:
mloess <- loess(wing2body ~ month_of_year, data=dfF)
xrange <- range(dfF$month_of_year)
xseq <- seq(from=xrange[1], to=xrange[2], length=80)
pred <- predict(mloess, newdata = data.frame(month_of_year = xseq), se=TRUE)
y = pred$fit
ci <- pred$se.fit * qt(0.95 / 2 + .5, pred$df)
ymin = y - ci
ymax = y + ci
loess.DF <- data.frame(x = xseq, y, ymin, ymax, se = pred$se.fit)
summary(loess.DF)
summary(mloess)
```

```{r}
# compare models
mlinear = glm(wing2body ~ month_of_year, data=df, family=gaussian)
mlinearF = glm(wing2body ~ month_of_year, data=dfF, family=gaussian)
mlinearM = glm(wing2body ~ month_of_year, data=dfM, family=gaussian)

summary(mlinear)$coeff[[8]] # significant for all (but only with K.elegans)
summary(mlinearF)$coeff # not significant for females (or when split by host plant)
summary(mlinearM)$coeff # significant for males (for K.elegans, not for C.corindum)
```

scale_colour_discrete(name ="Host Plant", labels=c("C. corindum", "K. elegans")) +

```{r}
p = ggplot() + 
  geom_point(data=dfF, mapping = aes(x = months_since_start, y = wing2body, colour=pophost)) +
  #geom_point(data=dfM, mapping = aes(x = months_since_start, y = wing2body, color="blue")) +
  #geom_line(colour='red',data = predF, aes(x=months_since_start, y=wing2body)) +
  geom_smooth(data=dfF, method="loess",
              mapping = aes(x = months_since_start, y = wing2body, colour=pophost, fill=pophost)) +
  #geom_smooth(data=dfM, colour="blue", method="loess",
  #            mapping = aes(x = months_since_start, y = wing2body, linetype = pophost)) +
  guides(fill = guide_legend(reverse = TRUE)) +
  scale_colour_discrete(name ="Host Plant", labels=c("C. corindum", "K. elegans")) +
  xlab("Months Since Start") + ylab("Wing-to-Body Ratio") +
  ggtitle("Females") 
p 
```

```{r}
#############wing morph plots

##Results to visualize: sex, host, months_since_start.

w_morph_summary<-aggregate(wing_morph_binom~sex*pophost*month_of_year, data=raw_data, FUN=mean)

```

```{r}
# create multiple linear model
df = w_morph_summary
dfF = df[df$sex=="F",]
dfFC = df[df$sex=="F" & df$pophost =="C.corindum",]
dfFK = df[df$sex=="F" & df$pophost =="K.elegans",]

dfM = df[df$sex=="M",]
#lmFC <- lm(wing2body ~ months_since_start, data=dfFC)
#predFC <- data.frame(wing2body = predict(lmFC, dfFC), months_since_start=dfFC$months_since_start)

ggplot() + 
  #geom_point(data=dfF, mapping = aes(x = month_of_year, y = wing_morph_binom, color="blue")) +
  #geom_point(data=dfM, mapping = aes(x = month_of_year, y = wing_morph_binom, color="red")) +
  #geom_line(color='red',data = predF, aes(x=months_since_start, y=wing2body)) +
  # geom_smooth(data=dfF, color="red",
  #             mapping = aes(x = month_of_year, y = wing_morph_binom, linetype = pophost)) +
  # geom_smooth(data=dfM, color="blue", 
  #             mapping = aes(x = month_of_year, y = wing_morph_binom, linetype = pophost))
    geom_smooth(data=df, color="blue", 
            mapping = aes(x = month_of_year, y = wing_morph_binom, linetype = sex))
```

```{r}
plot_splines = function(x,y) {
  fit0 <- lm(y~1)
  fit1 <- lm(y~x)
  fit2 <- lm(y~bs(x,5))
  
  print(anova(fit1,fit2))
  print(anova(fit0,fit2))
  print(anova(fit0,fit1))
  
  plot(x,y, pch=16)
  abline(fit1, col='red')
  xx <- seq(min(x),max(x), length.out=250)
  yy <- predict(fit2, data.frame(x=xx))
  lines(xx,yy, col='blue')
}

```

```{r}
dfF = df %>%
  filter(sex=="M" & pophost=="C.corindum")

x = dfF$month_of_year
y = dfF$wing_morph_binom

plot_splines(x,y)


dfF = df %>%
  filter(sex=="F" & pophost=="C.corindum")

x = dfF$month_of_year
y = dfF$wing_morph_binom

plot_splines(x,y)

```

```{r}
w_morph_summary<-aggregate(wing_morph_binom~sex_binom*pophost_binom*month_of_year, data=raw_data, FUN=mean)
df = w_morph_summary
data<-data.frame(R=df$wing_morph_binom, 
                 A=df$sex_binom, 
                 B=df$pophost_binom, 
                 C=(df$month_of_year))

model_script = paste0(source_path,"generic models-binomial glm 3-FF.R")
model_comparisonsAIC(model_script)
```
```{r}
anova(m0, m2, test="Chisq") # sex is marginally significant 
# summary(m2)  # sex is not significant
# nothing predicts wing_morph
```

```{r}
data<-data.frame(R=df$wing_morph_binom, 
                 A=df$sex_binom, 
                 B=df$pophost_binom, 
                 C=(df$month_of_year))
A = data$A
B = data$B
C = data$C
R = data$R

fit0 <- glm(R~1, family="binomial")
fit1 <- glm(R~B, family="binomial")
fit2 <- glm(R~bs(C,5), family="binomial") # b-splin basis for polynomial splines
fit3 <- glm(R~B + bs(C,5), family="binomial")

anova(fit0,fit1, test="Chisq") 
anova(fit0,fit2, test="Chisq")

?bs
```


```{r}
x <- rnorm(1000)
y <- sin(x) + rnorm(1000, 0, 0.5)

fit1 <- lm(y~x)
fit0 <- lm(y~1)
fit2 <- lm(y~bs(x,5))

anova(fit1,fit2)
anova(fit0,fit2)

plot(x,y, pch='.')
abline(fit1, col='red')
xx <- seq(min(x),max(x), length.out=250)
yy <- predict(fit2, data.frame(x=xx))
lines(xx,yy, col='blue')
```

